name: Public IP Address
version: "1.0.0"
slug: public-ip-address
description: Displays the public IP address as a sensor in Home Assistant
url: "https://github.com/kajkac/home-assistant-addon-ztemc801a/zte"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
image: ghcr.io/kajkac/zte-{arch}
