# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ZTE add-on
version: "1.2.0"
slug: zte
description: ZTE add-on
url: "https://github.com/Kajkac/home-assistant-addon-ztemc801a/new/main/zte"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "ZTE MC 801A"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
